industry_remap = {
  '11':'Agriculture',
  '21':'Mining',
  '22':'Utilities',
  '23':'Construction',
  '31':'Manufacturing',
  '32':'Manufacturing',
  '33':'Manufacturing',
  '42':'Wholesale Trade',
  '44':'Retail',
  '45':'Retail',
  '48':'Transportation',
  '49':'Transportation',
  '51':'Information',
  '52':'Finance',
  '53':'Real Estate',
  '54':'Professional Services',
  '55':'Finance',
  '56':'Administrative services',
  '61':'Educational Services',
  '62':'Health Care',
  '71':'Recreation',
  '72':'Hospitality',
  '81':'Other Services',
  '92':'Public',
  '00':'Unknown'}

country_code_remap = {
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Aland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthelemy",
  "BM": "Bermuda",
  "BN": "Brunei Darussalam",
  "BO": "Bolivia",
  "BQ": "Bonaire,  Saint Eustatius and Saba",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo, Democratic Republic of the",
  "CF": "Central African Republic",
  "CG": "Congo",
  "CH": "Switzerland",
  "CI": "Cote d'Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curacao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Faeroe Islands",
  "FM": "Micronesia (Federated States of)",
  "FO": "Falkland Islands (Malvinas)",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GS": "South Georgia and the South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HM": "Heard Island and McDonal Islands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Virgin Islands",
  "IQ": "Iraq",
  "IR": "Iran (Islamic Republic of)",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts and Nevis",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Lao People's Democratic Republic",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova, Republic of",
  "ME": "Montenegro",
  "MF": "Saint Martin (French part)",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "Macedonia, The former Yugoslav Republic of",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "Other": "Other",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territory, Occupied",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Reunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Saint Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard and Jan Mayen Islands",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome and Principe",
  "SV": "El Salvador",
  "SX": "Sint Maarten (Dutch part)",
  "SY": "Syrian Arab Republic",
  "SZ": "Swaziland",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan, Province of China",
  "TZ": "Tanzania, United Republic of",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "United States Minor Outlying Islands",
  "US": "United States of America",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "Unknown": "Unknown",
  "VA": "Holy See",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela (Bolivarian Republic of)",
  "VG": "British Virgin Islands",
  "VI": "United States Virgin Islands",
  "VN": "Viet Nam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna Islands",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
}

country_code_3_remap = {"AF":"AFG",
  "AL":"ALB",
  "DZ":"DZA",
  "AS":"ASM",
  "AD":"AND",
  "AO":"AGO",
  "AI":"AIA",
  "AQ":"ATA",
  "AG":"ATG",
  "AR":"ARG",
  "AM":"ARM",
  "AW":"ABW",
  "AU":"AUS",
  "AT":"AUT",
  "AZ":"AZE",
  "BS":"BHS",
  "BH":"BHR",
  "BD":"BGD",
  "BB":"BRB",
  "BY":"BLR",
  "BE":"BEL",
  "BZ":"BLZ",
  "BJ":"BEN",
  "BM":"BMU",
  "BT":"BTN",
  "BO":"BOL",
  "BA":"BIH",
  "BW":"BWA",
  "BV":"BVT",
  "BR":"BRA",
  "IO":"IOT",
  "BN":"BRN",
  "BG":"BGR",
  "BF":"BFA",
  "BI":"BDI",
  "KH":"KHM",
  "CM":"CMR",
  "CA":"CAN",
  "CV":"CPV",
  "KY":"CYM",
  "CF":"CAF",
  "TD":"TCD",
  "CL":"CHL",
  "CN":"CHN",
  "CX":"CXR",
  "CC":"CCK",
  "CO":"COL",
  "KM":"COM",
  "CG":"COG",
  "CD":"COD",
  "CK":"COK",
  "CR":"CRI",
  "CI":"CIV",
  "HR":"HRV",
  "CU":"CUB",
  "CY":"CYP",
  "CZ":"CZE",
  "DK":"DNK",
  "DJ":"DJI",
  "DM":"DMA",
  "DO":"DOM",
  "TP":"TMP",
  "EC":"ECU",
  "EG":"EGY",
  "SV":"SLV",
  "GQ":"GNQ",
  "ER":"ERI",
  "EE":"EST",
  "ET":"ETH",
  "FK":"FLK",
  "FO":"FRO",
  "FJ":"FJI",
  "FI":"FIN",
  "FR":"FRA",
  "FX":"FXX",
  "GF":"GUF",
  "PF":"PYF",
  "TF":"ATF",
  "GA":"GAB",
  "GM":"GMB",
  "GE":"GEO",
  "DE":"DEU",
  "GH":"GHA",
  "GI":"GIB",
  "GR":"GRC",
  "GL":"GRL",
  "GD":"GRD",
  "GP":"GLP",
  "GU":"GUM",
  "GT":"GTM",
  "GN":"GIN",
  "GW":"GNB",
  "GY":"GUY",
  "HT":"HTI",
  "HM":"HMD",
  "VA":"VAT",
  "HN":"HND",
  "HK":"HKG",
  "HU":"HUN",
  "IS":"ISL",
  "IN":"IND",
  "ID":"IDN",
  "IR":"IRN",
  "IQ":"IRQ",
  "IE":"IRL",
  "IL":"ISR",
  "IT":"ITA",
  "JM":"JAM",
  "JP":"JPN",
  "JO":"JOR",
  "KZ":"KAZ",
  "KE":"KEN",
  "KI":"KIR",
  "KP":"PRK",
  "KR":"KOR",
  "KW":"KWT",
  "KG":"KGZ",
  "LA":"LAO",
  "LV":"LVA",
  "LB":"LBN",
  "LS":"LSO",
  "LR":"LBR",
  "LY":"LBY",
  "LI":"LIE",
  "LT":"LTU",
  "LU":"LUX",
  "MO":"MAC",
  "MK":"MKD",
  "MG":"MDG",
  "MW":"MWI",
  "MY":"MYS",
  "MV":"MDV",
  "ML":"MLI",
  "MT":"MLT",
  "MH":"MHL",
  "MQ":"MTQ",
  "MR":"MRT",
  "MU":"MUS",
  "YT":"MYT",
  "MX":"MEX",
  "FM":"FSM",
  "MD":"MDA",
  "MC":"MCO",
  "MN":"MNG",
  "ME":"MNE",
  "MS":"MSR",
  "MA":"MAR",
  "MZ":"MOZ",
  "MM":"MMR",
  "NA":"NAM",
  "NR":"NRU",
  "NP":"NPL",
  "NL":"NLD",
  "AN":"ANT",
  "NC":"NCL",
  "NZ":"NZL",
  "NI":"NIC",
  "NE":"NER",
  "NG":"NGA",
  "NU":"NIU",
  "NF":"NFK",
  "MP":"MNP",
  "NO":"NOR",
  "OM":"OMN",
  "PK":"PAK",
  "PW":"PLW",
  "PA":"PAN",
  "PG":"PNG",
  "PY":"PRY",
  "PE":"PER",
  "PH":"PHL",
  "PN":"PCN",
  "PL":"POL",
  "PS":"PLE",
  "PT":"PRT",
  "PR":"PRI",
  "QA":"QAT",
  "RE":"REU",
  "RO":"ROM",
  "RU":"RUS",
  "RW":"RWA",
  "KN":"KNA",
  "LC":"LCA",
  "VC":"VCT",
  "WS":"WSM",
  "SM":"SMR",
  "ST":"STP",
  "SA":"SAU",
  "SN":"SEN",
  "RS":"SRB",
  "SC":"SYC",
  "SL":"SLE",
  "SG":"SGP",
  "SK":"SVK",
  "SI":"SVN",
  "SB":"SLB",
  "SO":"SOM",
  "ZA":"ZAF",
  "SS":"SSD",
  "GS":"SGS",
  "ES":"ESP",
  "LK":"LKA",
  "SH":"SHN",
  "PM":"SPM",
  "SD":"SDN",
  "SR":"SUR",
  "SJ":"SJM",
  "SZ":"SWZ",
  "SE":"SWE",
  "CH":"CHE",
  "SY":"SYR",
  "TW":"TWN",
  "TJ":"TJK",
  "TZ":"TZA",
  "TH":"THA",
  "TG":"TGO",
  "TK":"TKL",
  "TO":"TON",
  "TT":"TTO",
  "TN":"TUN",
  "TR":"TUR",
  "TM":"TKM",
  "TC":"TCA",
  "TV":"TUV",
  "UG":"UGA",
  "UA":"UKR",
  "AE":"ARE",
  "GB":"GBR",
  "US":"USA",
  "UM":"UMI",
  "UY":"URY",
  "UZ":"UZB",
  "VU":"VUT",
  "VE":"VEN",
  "VN":"VNM",
  "VG":"VGB",
  "VI":"VIR",
  "WF":"WLF",
  "EH":"ESH",
  "YE":"YEM",
  "ZM":"ZMB",
  "ZW":"ZWE"}